### ISSUE TITLE
Exception in ControllerIT after another test fails

### ISSUE THREAD

**Issue by StCostea** [reaktivity/k3po-nukleus-ext.java#26]
This is happening only in Eclipse, with k3po running externally from a command line. The maven build seems to work properly.

While running all tests under nukleus-http2.java, after some other tests are failing, all 4 tests under ControllerIT are failing with the following exception in the k3po log:

```
javax.el.ELException: java.io.IOException: The requested operation cannot be performed on a file with a user-mapped section open
        at javax.el.BeanELResolver.invoke(BeanELResolver.java:502)
        at javax.el.CompositeELResolver.invoke(CompositeELResolver.java:397)
        at javax.el.CompositeELResolver.invoke(CompositeELResolver.java:397)
        at de.odysseus.el.util.SimpleResolver.invoke(SimpleResolver.java:135)
        at de.odysseus.el.tree.impl.ast.AstMethod.eval(AstMethod.java:91)
        at de.odysseus.el.tree.impl.ast.AstMethod.eval(AstMethod.java:100)
        at de.odysseus.el.tree.impl.ast.AstEval.eval(AstEval.java:51)
        at de.odysseus.el.tree.impl.ast.AstNode.getValue(AstNode.java:31)
        at de.odysseus.el.TreeValueExpression.getValue(TreeValueExpression.java:122)
        at org.kaazing.k3po.lang.internal.el.ExpressionFactoryUtils.synchronizedValue(ExpressionFactoryUtils.java:58)
        at org.kaazing.k3po.lang.internal.ast.value.AstExpressionValue.getValue(AstExpressionValue.java:43)
        at org.kaazing.k3po.lang.internal.ast.AstPropertyNode.resolve(AstPropertyNode.java:58)
        at org.kaazing.k3po.driver.internal.behavior.visitor.GenerateConfigurationVisitor.visit(GenerateConfigurationVisitor.java:241)
        at org.kaazing.k3po.driver.internal.behavior.visitor.GenerateConfigurationVisitor.visit(GenerateConfigurationVisitor.java:162)
        at org.kaazing.k3po.lang.internal.ast.AstPropertyNode.accept(AstPropertyNode.java:34)
        at org.kaazing.k3po.driver.internal.behavior.visitor.GenerateConfigurationVisitor.visit(GenerateConfigurationVisitor.java:227)
        at org.kaazing.k3po.driver.internal.behavior.visitor.GenerateConfigurationVisitor.visit(GenerateConfigurationVisitor.java:162)
        at org.kaazing.k3po.lang.internal.ast.AstScriptNode.accept(AstScriptNode.java:46)
        at org.kaazing.k3po.driver.internal.Robot.prepare(Robot.java:146)
        at org.kaazing.k3po.driver.internal.control.handler.ControlServerHandler.prepareReceived(ControlServerHandler.java:189)
        at org.kaazing.k3po.driver.internal.control.handler.ControlUpstreamHandler.messageReceived(ControlUpstreamHandler.java:40)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: The requested operation cannot be performed on a file with a user-mapped section open
        at java.io.RandomAccessFile.setLength(Native Method)
        at org.agrona.IoUtil.createEmptyFile(IoUtil.java:224)
        at org.agrona.IoUtil.mapNewFile(IoUtil.java:305)
        at org.reaktivity.specification.nukleus.Functions$Helper$ControlHelper$Eager.<init>(Functions.java:269)
        at org.reaktivity.specification.nukleus.Functions$Helper$ControlHelper$Eager.<init>(Functions.java:252)
        at org.reaktivity.specification.nukleus.Functions$Helper.controlNew(Functions.java:113)
        at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.el.BeanELResolver.invoke(BeanELResolver.java:500)
        ... 42 more
```

Not sure how easy it will be to reproduce it in some other environment.

**Comment by StCostea** [comment]
Running only ControllerIT will pass the tests.

**Comment by dpwspoon** [comment]
Please confirm you are running with 0.13.  I also hit a file related issue (not this one specifically) in 0.12 that was resolved in 0.13.

**Comment by StCostea** [comment]
If you are talking about k3po.nukleus.ext.version, it is currently 0.12, but it is the same also on develop. Should I change it in my env to 0.13 ?

**Comment by StCostea** [comment]
I just checked, error is the same with 0.13.

Also, an additional information: after this error, if I try a build without stopping the k3po, the maven build fails with the error ` Failed to delete D:\Repositories\nukleus-http2.java\target\nukleus-itests\http2\control`. Normally, a build without tests will pass even if k3po is started.
